"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { formatDistanceToNow } from "date-fns";
import { id as dfId, enUS } from "date-fns/locale";
import {
  CornerDownRight,
  Globe,
  Loader2,
  MessageCircle,
  Send,
  Sparkles,
  X,
} from "lucide-react";

import type { Language } from "@/i18n/config";
import type { CommentNode } from "@/lib/queries";
import {
  blogChannel,
  getPusherClient,
  PUSHER_EVENTS,
  type PusherCommentPayload,
  type PusherRejectedPayload,
} from "@/lib/pusher/client";

interface CommentsProps {
  slug: string;
  initialComments: CommentNode[];
  initialCount: number;
  lang: Language;
}

interface FormDraft {
  authorName: string;
  authorEmail: string;
  authorWebsite: string;
  body: string;
}

const LABELS = {
  en: {
    title: "Comments",
    empty: "No comments yet — be the first to start the conversation.",
    pending:
      "AI is reviewing your comment for safety — should appear in a few seconds…",
    posted: "✓ Posted! Your comment is live.",
    rejected:
      "Your comment didn't pass automated moderation. Try keeping things civil and constructive.",
    name: "Name",
    email: "Email (won't be published)",
    website: "Website (optional)",
    body: "Your comment",
    submit: "Post comment",
    submitting: "Posting…",
    reply: "Reply",
    cancelReply: "Cancel",
    replyingTo: "Replying to",
    showReplies: (n: number) => `${n} ${n === 1 ? "reply" : "replies"}`,
    hideReplies: "Hide replies",
    storedNoticeTitle: "Saved for next time",
    storedNotice:
      "Your name + email are stored in this browser only, so you don't have to retype them.",
    forget: "Forget me",
    failed: "Couldn't send your comment. Try again?",
    aiReply: "AI auto-reply",
    aiReplyHelp: "Generated by AI based on the post — Dedy reads them later.",
    live: "Live",
  },
  id: {
    title: "Komentar",
    empty: "Belum ada komentar — kamu yang pertama nih!",
    pending:
      "AI sedang memeriksa komentar kamu — bakal muncul dalam beberapa detik…",
    posted: "✓ Terkirim! Komentar kamu sudah tayang.",
    rejected:
      "Komentar kamu tidak lolos moderasi otomatis. Coba pakai bahasa yang lebih sopan ya.",
    name: "Nama",
    email: "Email (tidak akan dipublikasikan)",
    website: "Website (opsional)",
    body: "Komentar kamu",
    submit: "Kirim komentar",
    submitting: "Mengirim…",
    reply: "Balas",
    cancelReply: "Batal",
    replyingTo: "Membalas",
    showReplies: (n: number) => `${n} balasan`,
    hideReplies: "Sembunyikan balasan",
    storedNoticeTitle: "Disimpan untuk lain kali",
    storedNotice:
      "Nama + email kamu disimpan hanya di browser ini, jadi ga perlu ngetik ulang.",
    forget: "Hapus data saya",
    failed: "Gagal kirim komentar. Coba lagi?",
    aiReply: "Balasan otomatis AI",
    aiReplyHelp: "Dibuat AI berdasarkan isi postingan — Dedy baca nanti.",
    live: "Live",
  },
} satisfies Record<Language, unknown>;

const STORAGE_KEY = "blog_comment_author";
const MAX_VISIBLE_DEPTH = 3;

interface StoredAuthor {
  authorName: string;
  authorEmail: string;
  authorWebsite: string;
}

function loadStoredAuthor(): StoredAuthor | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<StoredAuthor>;
    return {
      authorName: parsed.authorName ?? "",
      authorEmail: parsed.authorEmail ?? "",
      authorWebsite: parsed.authorWebsite ?? "",
    };
  } catch {
    return null;
  }
}

function saveStoredAuthor(value: StoredAuthor) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(value));
  } catch {
    /* ignore quota errors */
  }
}

/* ─── Tree mutation helpers ───────────────────────────────── */

function commentExists(tree: CommentNode[], id: string): boolean {
  for (const node of tree) {
    if (node.id === id) return true;
    if (commentExists(node.replies, id)) return true;
  }
  return false;
}

function insertComment(tree: CommentNode[], next: CommentNode): CommentNode[] {
  if (!next.parentId) {
    // Root insertion — append at end so newest sits at the bottom (matches
    // server-side ordering, which is createdAt asc).
    return [...tree, next];
  }
  return tree.map((node) => {
    if (node.id === next.parentId) {
      return { ...node, replies: [...node.replies, next] };
    }
    return { ...node, replies: insertComment(node.replies, next) };
  });
}

function payloadToNode(p: PusherCommentPayload): CommentNode {
  return {
    id: p.id,
    parentId: p.parentId,
    authorName: p.authorName,
    authorWebsite: p.authorWebsite,
    body: p.body,
    createdAt: new Date(p.createdAt),
    isAiReply: p.isAiReply,
    replies: [],
  };
}

/* ─── Top component ───────────────────────────────────────── */

export function Comments({
  slug,
  initialComments,
  initialCount,
  lang,
}: CommentsProps) {
  const labels = LABELS[lang];
  const dateLocale = lang === "id" ? dfId : enUS;

  const [comments, setComments] = useState<CommentNode[]>(initialComments);
  const [count, setCount] = useState(initialCount);
  const [replyingTo, setReplyingTo] = useState<CommentNode | null>(null);
  const [stored, setStored] = useState<StoredAuthor | null>(null);
  const [realtimeReady, setRealtimeReady] = useState(false);

  // Track each comment we just submitted so we can light up the right notice
  // when its moderation result arrives over Pusher.
  const pendingIdsRef = useRef<Set<string>>(new Set());
  const [submissionState, setSubmissionState] = useState<
    | { kind: "idle" }
    | { kind: "pending"; message: string }
    | { kind: "posted"; message: string }
    | { kind: "rejected"; message: string }
  >({ kind: "idle" });
  const submissionStateRef = useRef(submissionState);
  submissionStateRef.current = submissionState;

  useEffect(() => {
    setStored(loadStoredAuthor());
  }, []);

  // Subscribe to the blog's real-time channel for live moderation results.
  useEffect(() => {
    const pusher = getPusherClient();
    if (!pusher) return;

    const channel = pusher.subscribe(blogChannel(slug));

    const onConnected = () => setRealtimeReady(true);
    pusher.connection.bind("connected", onConnected);
    if (pusher.connection.state === "connected") setRealtimeReady(true);

    const onNew = (payload: PusherCommentPayload) => {
      setComments((prev) => {
        if (commentExists(prev, payload.id)) return prev;
        return insertComment(prev, payloadToNode(payload));
      });
      setCount((n) => n + 1);

      if (pendingIdsRef.current.has(payload.id)) {
        pendingIdsRef.current.delete(payload.id);
        setSubmissionState({ kind: "posted", message: labels.posted });
        // Fade away after a moment.
        setTimeout(() => {
          setSubmissionState((s) =>
            s.kind === "posted" ? { kind: "idle" } : s
          );
        }, 5000);
      }
    };

    const onRejected = (payload: PusherRejectedPayload) => {
      if (pendingIdsRef.current.has(payload.id)) {
        pendingIdsRef.current.delete(payload.id);
        setSubmissionState({
          kind: "rejected",
          message: payload.reason || labels.rejected,
        });
      }
    };

    channel.bind(PUSHER_EVENTS.COMMENT_NEW, onNew);
    channel.bind(PUSHER_EVENTS.COMMENT_REJECTED, onRejected);

    return () => {
      channel.unbind(PUSHER_EVENTS.COMMENT_NEW, onNew);
      channel.unbind(PUSHER_EVENTS.COMMENT_REJECTED, onRejected);
      pusher.connection.unbind("connected", onConnected);
      pusher.unsubscribe(blogChannel(slug));
    };
    // labels depends on `lang`; effect re-runs only when slug or lang changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug, lang]);

  const trackPendingSubmission = useCallback(
    (id: string) => {
      pendingIdsRef.current.add(id);
      setSubmissionState({ kind: "pending", message: labels.pending });

      // Fallback: if no Pusher event arrives within 60s, gracefully tell the
      // user their comment is queued (the API still inserted it as PENDING,
      // so an admin can approve it manually if AI was unavailable).
      window.setTimeout(() => {
        if (pendingIdsRef.current.has(id)) {
          pendingIdsRef.current.delete(id);
          setSubmissionState((current) =>
            current.kind === "pending"
              ? {
                  kind: "posted",
                  message:
                    lang === "id"
                      ? "Komentar kamu masuk antrean moderasi. Akan tampil setelah disetujui."
                      : "Your comment is queued for review. It will appear once approved.",
                }
              : current
          );
        }
      }, 60_000);
    },
    [lang, labels.pending]
  );

  return (
    <section
      id="comments"
      aria-labelledby="comments-heading"
      className="mt-16 border-t border-white/10 pt-12"
    >
      <div className="flex items-center gap-2">
        <MessageCircle className="text-accent-soft" size={20} aria-hidden />
        <h2
          id="comments-heading"
          className="font-display text-2xl font-bold tracking-tight text-white"
        >
          {labels.title}
          {count > 0 && (
            <span className="ml-2 text-base font-normal text-white/50">
              ({count})
            </span>
          )}
        </h2>
        {realtimeReady && (
          <span
            title={labels.live}
            className="ml-1 inline-flex items-center gap-1 rounded-full border border-emerald-400/30 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-emerald-300"
          >
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" />
            {labels.live}
          </span>
        )}
      </div>

      {comments.length === 0 ? (
        <p className="mt-6 rounded-2xl border border-dashed border-white/10 bg-white/[0.02] px-5 py-10 text-center text-sm text-white/55">
          {labels.empty}
        </p>
      ) : (
        <ul className="mt-8 space-y-6">
          {comments.map((c) => (
            <CommentItem
              key={c.id}
              node={c}
              depth={0}
              onReply={setReplyingTo}
              dateLocale={dateLocale}
              labels={labels}
            />
          ))}
        </ul>
      )}

      <CommentForm
        slug={slug}
        lang={lang}
        labels={labels}
        replyingTo={replyingTo}
        onCancelReply={() => setReplyingTo(null)}
        stored={stored}
        onPersistAuthor={(s) => {
          saveStoredAuthor(s);
          setStored(s);
        }}
        onForgetAuthor={() => {
          window.localStorage.removeItem(STORAGE_KEY);
          setStored(null);
        }}
        onSubmitted={(id) => {
          setReplyingTo(null);
          trackPendingSubmission(id);
        }}
        submissionState={submissionState}
      />
    </section>
  );
}

/* ─── Single comment + nested replies ─────────────────────── */

interface CommentItemProps {
  node: CommentNode;
  depth: number;
  onReply: (node: CommentNode) => void;
  dateLocale: typeof enUS;
  labels: (typeof LABELS)[Language];
}

function CommentItem({
  node,
  depth,
  onReply,
  dateLocale,
  labels,
}: CommentItemProps) {
  const [collapsed, setCollapsed] = useState(false);
  const hasReplies = node.replies.length > 0;
  const indentDepth = Math.min(depth, MAX_VISIBLE_DEPTH);

  return (
    <li
      className={[
        "rounded-2xl border bg-ink-900/40",
        node.isAiReply
          ? "border-accent-soft/30 bg-accent-soft/[0.04]"
          : "border-white/10",
        depth > 0 ? "ml-3 sm:ml-6" : "",
      ].join(" ")}
      style={
        indentDepth > 0
          ? { borderLeft: "2px solid rgba(255,255,255,0.08)" }
          : undefined
      }
    >
      <article className="px-4 py-4 sm:px-5">
        <header className="flex flex-wrap items-baseline gap-x-2 gap-y-1">
          <span className="text-sm font-semibold text-white">
            {node.authorName}
          </span>
          {node.isAiReply && (
            <span
              title={labels.aiReplyHelp}
              className="inline-flex items-center gap-1 rounded-full border border-accent-soft/40 bg-accent-soft/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-accent-soft"
            >
              <Sparkles size={10} aria-hidden />
              {labels.aiReply}
            </span>
          )}
          {node.authorWebsite && !node.isAiReply && (
            <a
              href={node.authorWebsite}
              target="_blank"
              rel="nofollow noreferrer"
              className="inline-flex items-center gap-1 text-xs text-accent-soft/80 hover:text-accent-soft"
            >
              <Globe size={11} aria-hidden />
              <span className="truncate">
                {prettyHostname(node.authorWebsite)}
              </span>
            </a>
          )}
          <time
            dateTime={node.createdAt.toString()}
            className="text-xs text-white/45"
          >
            ·{" "}
            {formatDistanceToNow(new Date(node.createdAt), {
              addSuffix: true,
              locale: dateLocale,
            })}
          </time>
        </header>

        <p className="mt-2 whitespace-pre-line text-[0.95rem] leading-relaxed text-white/85">
          {node.body}
        </p>

        <div className="mt-3 flex items-center gap-3 text-xs">
          <button
            type="button"
            onClick={() => onReply(node)}
            className="inline-flex items-center gap-1 text-white/55 transition hover:text-accent-soft"
          >
            <CornerDownRight size={12} aria-hidden />
            {labels.reply}
          </button>
          {hasReplies && (
            <button
              type="button"
              onClick={() => setCollapsed((v) => !v)}
              className="text-white/55 transition hover:text-white"
            >
              {collapsed
                ? labels.showReplies(node.replies.length)
                : labels.hideReplies}
            </button>
          )}
        </div>
      </article>

      {hasReplies && !collapsed && (
        <ul className="space-y-3 pb-4 pl-2 pr-4 sm:pl-3 sm:pr-5">
          {node.replies.map((r) => (
            <CommentItem
              key={r.id}
              node={r}
              depth={depth + 1}
              onReply={onReply}
              dateLocale={dateLocale}
              labels={labels}
            />
          ))}
        </ul>
      )}
    </li>
  );
}

function prettyHostname(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

/* ─── Submission form ─────────────────────────────────────── */

type SubmissionState =
  | { kind: "idle" }
  | { kind: "pending"; message: string }
  | { kind: "posted"; message: string }
  | { kind: "rejected"; message: string };

interface CommentFormProps {
  slug: string;
  lang: Language;
  labels: (typeof LABELS)[Language];
  replyingTo: CommentNode | null;
  onCancelReply: () => void;
  stored: StoredAuthor | null;
  onPersistAuthor: (s: StoredAuthor) => void;
  onForgetAuthor: () => void;
  /** Called with the new comment id after a successful POST. */
  onSubmitted: (id: string) => void;
  submissionState: SubmissionState;
}

function CommentForm({
  slug,
  lang,
  labels,
  replyingTo,
  onCancelReply,
  stored,
  onPersistAuthor,
  onForgetAuthor,
  onSubmitted,
  submissionState,
}: CommentFormProps) {
  const [draft, setDraft] = useState<FormDraft>(() => ({
    authorName: "",
    authorEmail: "",
    authorWebsite: "",
    body: "",
  }));
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!stored) return;
    setDraft((d) => ({
      ...d,
      authorName: d.authorName || stored.authorName,
      authorEmail: d.authorEmail || stored.authorEmail,
      authorWebsite: d.authorWebsite || stored.authorWebsite,
    }));
  }, [stored]);

  const update = (key: keyof FormDraft, value: string) =>
    setDraft((d) => ({ ...d, [key]: value }));

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (pending) return;
    setError(null);
    setPending(true);

    try {
      const res = await fetch(
        `/api/blog/${encodeURIComponent(slug)}/comments`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            ...draft,
            parentId: replyingTo?.id,
            lang,
          }),
        }
      );

      const data = (await res.json().catch(() => ({}))) as {
        error?: string;
        message?: string;
        id?: string;
      };

      if (!res.ok) {
        setError(data.error ?? labels.failed);
        return;
      }

      onPersistAuthor({
        authorName: draft.authorName,
        authorEmail: draft.authorEmail,
        authorWebsite: draft.authorWebsite,
      });

      setDraft((d) => ({ ...d, body: "" }));
      if (data.id) onSubmitted(data.id);
    } catch (err) {
      setError(err instanceof Error ? err.message : labels.failed);
    } finally {
      setPending(false);
    }
  };

  const fieldClass =
    "w-full rounded-lg border border-white/10 bg-ink-900/60 px-3 py-2 text-sm text-white placeholder-white/40 focus:border-accent-soft/60 focus:outline-none focus:ring-2 focus:ring-accent-soft/20";

  const replyingToBadge = useMemo(() => {
    if (!replyingTo) return null;
    return (
      <div className="flex items-center justify-between gap-2 rounded-lg border border-accent-soft/30 bg-accent-soft/5 px-3 py-2 text-xs text-accent-soft">
        <span>
          {labels.replyingTo}{" "}
          <span className="font-semibold">{replyingTo.authorName}</span>
        </span>
        <button
          type="button"
          onClick={onCancelReply}
          className="inline-flex items-center gap-1 rounded px-1 hover:bg-white/5"
          aria-label={labels.cancelReply}
        >
          <X size={12} />
          {labels.cancelReply}
        </button>
      </div>
    );
  }, [replyingTo, onCancelReply, labels]);

  return (
    <form onSubmit={submit} className="mt-10 space-y-3" noValidate>
      {replyingToBadge}

      {submissionState.kind === "pending" && (
        <div className="flex items-start gap-2 rounded-lg border border-amber-300/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-100">
          <Loader2
            size={14}
            className="mt-0.5 shrink-0 animate-spin"
            aria-hidden
          />
          <span>{submissionState.message}</span>
        </div>
      )}
      {submissionState.kind === "posted" && (
        <div className="rounded-lg border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          {submissionState.message}
        </div>
      )}
      {submissionState.kind === "rejected" && (
        <div className="rounded-lg border border-rose-400/30 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">
          {submissionState.message}
        </div>
      )}

      {error && (
        <div className="rounded-lg border border-rose-400/30 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">
          {error}
        </div>
      )}

      <div className="grid gap-3 sm:grid-cols-2">
        <input
          required
          name="authorName"
          placeholder={labels.name}
          value={draft.authorName}
          onChange={(e) => update("authorName", e.target.value)}
          maxLength={60}
          className={fieldClass}
        />
        <input
          required
          type="email"
          name="authorEmail"
          placeholder={labels.email}
          value={draft.authorEmail}
          onChange={(e) => update("authorEmail", e.target.value)}
          maxLength={120}
          className={fieldClass}
        />
        <input
          type="url"
          name="authorWebsite"
          placeholder={labels.website}
          value={draft.authorWebsite}
          onChange={(e) => update("authorWebsite", e.target.value)}
          maxLength={200}
          className={`${fieldClass} sm:col-span-2`}
        />
      </div>

      <textarea
        required
        name="body"
        placeholder={labels.body}
        value={draft.body}
        onChange={(e) => update("body", e.target.value)}
        rows={4}
        maxLength={2000}
        className={`${fieldClass} resize-y leading-relaxed`}
      />

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="text-[11px] text-white/40">
          {stored?.authorName ? (
            <>
              {labels.storedNotice}{" "}
              <button
                type="button"
                onClick={onForgetAuthor}
                className="underline decoration-white/30 underline-offset-2 transition hover:text-white"
              >
                {labels.forget}
              </button>
            </>
          ) : null}
        </div>

        <button
          type="submit"
          disabled={pending}
          className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-indigo-500 to-fuchsia-500 px-5 py-2 text-sm font-medium text-white shadow-lg transition hover:from-indigo-400 hover:to-fuchsia-400 disabled:opacity-60"
        >
          {pending ? (
            <Loader2 size={14} className="animate-spin" aria-hidden />
          ) : (
            <Send size={14} aria-hidden />
          )}
          {pending ? labels.submitting : labels.submit}
        </button>
      </div>
    </form>
  );
}
